export const GETCUSTOMER_START = "GETCUSTOMER_START";
export const GETCUSTOMER_SUCCESS = "GETCUSTOMER_SUCCESS";
export const GETCUSTOMER_FAIL = "GETCUSTOMER_FAIL";

export const DELETECUSTOMER_START = "DELETECUSTOMER_START";
export const DELETECUSTOMER_SUCCESS = "DELETECUSTOMER_SUCCESS";
export const DELETECUSTOMER_FAIL = "DELETECUSTOMER_FAIL";

export const GETCOMPANY_START = "GETCOMPANY_START";
export const GETCOMPANY_SUCCESS = "GETCOMPANY_SUCCESS";
export const GETCOMPANY_FAIL = "GETCOMPANY_FAIL";

export const DELETECOMPANY_START = "DELETECOMPANY_START";
export const DELETECOMPANY_SUCCESS = "DELETECOMPANY_SUCCESS";
export const DELETECOMPANY_FAIL = "DELETECOMPANY_FAIL";

export const GETCOMMENT_START = "GETCOMMENT_START";
export const GETCOMMENT_SUCCESS = "GETCOMMENT_SUCCESS";
export const GETCOMMENT_FAIL = "GETCOMMENT_FAIL";

export const DELETECOMMENT_START = "DELETECOMMENT_START";
export const DELETECOMMENT_SUCCESS = "DELETECOMMENT_SUCCESS";
export const DELETECOMMENT_FAIL = "DELETECOMMENT_FAIL";

export const GETTOUR_START = "GETTOUR_START";
export const GETTOUR_SUCCESS = "GETTOUR_SUCCESS";
export const GETTOUR_FAIL = "GETTOUR_FAIL";

export const DELETETOUR_START = "DELETETOUR_START";
export const DELETETOUR_SUCCESS = "DELETETOUR_SUCCESS";
export const DELETETOUR_FAIL = "DELETETOUR_FAIL";