export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ADDTOUR_START = "ADDTOUR_START";
export const ADDTOUR_SUCCESS = "ADDTOUR_SUCCESS";
export const ADDTOUR_FAIL = "ADDTOUR_FAIL";

export const GETTOURS_START = "GETTOURS_START";
export const GETTOURS_SUCCESS = "GETTOURS_SUCCESS";
export const GETTOURS_FAIL = "GETTOURS_FAIL";

export const GETTOURSPLACE_START = "GETTOURSPLACE_START";
export const GETTOURSPLACE_SUCCESS = "GETTOURSPLACE_SUCCESS";
export const GETTOURSPLACE_FAIL = "GETTOURSPLACE_FAIL";

export const GETTOURSNAME_START = "GETTOURSNAME_START";
export const GETTOURSNAME_SUCCESS = "GETTOURSNAME_SUCCESS";
export const GETTOURSNAME_FAIL = "GETTOURSNAME_FAIL";

export const GETTOURSSALE_START = "GETTOURSSALE_START";
export const GETTOURSSALE_SUCCESS = "GETTOURSSALE_SUCCESS";
export const GETTOURSSALE_FAIL = "GETTOURSSALE_FAIL";

export const GETTOURSPRICE_START = "GETTOURSPRICE_START";
export const GETTOURSPRICE_SUCCESS = "GETTOURSPRICE_SUCCESS";
export const GETTOURSPRICE_FAIL = "GETTOURSPRICE_FAIL";

export const GETTOURSCOMPANY_START = "GETTOURSCOMPANY_START";
export const GETTOURSCOMPANY_SUCCESS = "GETTOURSCOMPANY_SUCCESS";
export const GETTOURSCOMPANY_FAIL = "GETTOURSCOMPANY_FAIL";

export const GETONETOUR_START = "GETONETOUR_START";
export const GETONETOUR_SUCCESS = "GETONETOUR_SUCCESS";
export const GETONETOUR_FAIL = "GETONETOUR_FAIL";

export const EDITTOUR_START = "EDITTOUR_START";
export const EDITTOUR_SUCCESS = "EDITTOUR_SUCCESS";
export const EDITTOUR_FAIL = "EDITTOUR_FAIL";

export const DELETETOUR_START = "DELETETOUR_START";
export const DELETETOUR_SUCCESS = "DELETETOUR_SUCCESS";
export const DELETETOUR_FAIL = "DELETETOUR_FAIL"

export const GETCATEGORY_START = "GETCATEGORY_START";
export const GETCATEGORY_SUCCESS = "GETCATEGORY_SUCCESS";
export const GETCATEGORY_FAIL = "GETCATEGORY_FAIL";

export const BOOKTOUR_START = "BOOKTOUR_START";
export const BOOKTOUR_SUCCESS = "BOOKTOUR_SUCCESS";
export const BOOKTOUR_FAIL = "BOOKTOUR_FAIL";

export const GETCOMMENT_START = "GETCOMMENT_START";
export const GETCOMMENT_SUCCESS = "GETCOMMENT_SUCCESS";
export const GETCOMMENT_FAIL = "GETCOMMENT_FAIL";

export const GETTOUROFCOMPANY_START = "GETTOUTOFCOMPANY_START";
export const GETTOUROFCOMPANY_SUCCESS = "GETTOUTOFCOMPANY_SUCCESS";
export const GETTOUROFCOMPANY_FAIL = "GETTOUTOFCOMPANY_FAIL";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const GETTOURSSALEHOME_START = "GETTOURSSALEHOME_START";
export const GETTOURSSALEHOME_SUCCESS = "GETTOURSSALEHOME_SUCCESS";
export const GETTOURSSALEHOME_FAIL = "GETTOURSSALEHOME_FAIL";

export const ADDCOMMENT_START = "ADDCOMMENT_START";
export const ADDCOMMENT_SUCCESS = "ADDCOMMENT_SUCCESS";
export const ADDCOMMENT_FAIL = "ADDCOMMENT_FAIL";

export const GETUSER_START = "GETUSER_START";
export const GETUSER_SUCCESS = "GETUSER_SUCCESS";
export const GETUSER_FAIL = "GETUSER_FAIL";

export const EDITUSER_START = "EDITUSER_START";
export const EDITUSER_SUCCESS = "EDITUSER_SUCCESS";
export const EDITUSER_FAIL = "EDITUSER_FAIL";