export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ADDTOUR_START = "ADDTOUR_START";
export const ADDTOUR_SUCCESS = "ADDTOUR_SUCCESS";
export const ADDTOUR_FAIL = "ADDTOUR_FAIL";

export const GETTOURS_START = "GETTOURS_START";
export const GETTOURS_SUCCESS = "GETTOURS_SUCCESS";
export const GETTOURS_FAIL = "GETTOURS_FAIL";

export const GETONETOUR_START = "GETONETOUR_START";
export const GETONETOUR_SUCCESS = "GETONETOUR_SUCCESS";
export const GETONETOUR_FAIL = "GETONETOUR_FAIL";

export const EDITTOUR_START = "EDITTOUR_START";
export const EDITTOUR_SUCCESS = "EDITTOUR_SUCCESS";
export const EDITTOUR_FAIL = "EDITTOUR_FAIL";

export const DELETETOUR_START = "DELETETOUR_START";
export const DELETETOUR_SUCCESS = "DELETETOUR_SUCCESS";
export const DELETETOUR_FAIL = "DELETETOUR_FAIL"

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";